---
name: Upstream Sync
'on':
  schedule:
    - cron: "15 8 * * 1"
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
jobs:
  synchronise-2023-1:
    name: Synchronise 2023.1
    uses: stackhpc/.github/.github/workflows/upstream-sync.yml@main
    with:
      release_series: 2023.1
  synchronise-wallaby:
    name: Synchronise wallaby
    uses: stackhpc/.github/.github/workflows/upstream-sync.yml@main
    with:
      release_series: wallaby
